name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Type Check
        run: |
          pnpm run typecheck

  format-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Format Check
        run: |
          pnpm run fmt:check

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Lint
        run: |
          pnpm run lint
